# 挂载模式 Dockerfile
FROM registry.cn-hangzhou.aliyuncs.com/panxu/php:8.4-fpm-nginx-alpine

WORKDIR /app

RUN rm -rf /etc/nginx/conf.d/default.conf
RUN mkdir -p /run/nginx /var/log/nginx

EXPOSE 80

# 容器启动命令
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]