version: '3.8'

services:
  webman:
    container_name: webman1_6-volume
    image: webman1_6:volume
    working_dir: /app
    build:
      context: ..
      dockerfile: docker/Dockerfile.volume
    ports:
      - "8053:8787"
    volumes:
      - ../:/app:delegated   # 这里改为项目根目录
      - webman_vendor:/app/vendor  # 使用具名卷
    command: ["php", "start.php", "start"]
    restart: always
    tty: true
    environment:
      - WEBMAN_ENV=dev
volumes:
  webman_vendor: