version: "3.8"
services:
  laravel-app:
    container_name: laravel11
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: laravel11
    ports:
      - "8078:80"
    environment:
      - APP_ENV=production
    restart: unless-stopped
